### ISSUE TITLE
Object.keys(dna) called on non-object

### ISSUE THREAD

**Issue by outbounder** [camplight/organic-dna-resolve#1]
Using node v0.10.30 the following error occurs:

```
/home/outbounder/projects/outbounder/organic-stem-skeleton/node_modules/organic-dna-resolve/index.js:24
  Object.keys(dna).forEach(function(key) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at walk (/home/outbounder/projects/outbounder/organic-stem-skeleton/node_modules/organic-dna-resolve/index.js:24:10)
    at /home/outbounder/projects/outbounder/organic-stem-skeleton/node_modules/organic-dna-resolve/index.js:42:18
```

Using node v4.2.3 the above is not present.

----

I guess either `engine` should be added to `package.json` and/or `Object.keys` usage should be refactored to support older javascript versions...

**Comment by multi** [comment]
@outbounder thanks, fixed in v0.0.2 - switched from Object.keys to for/in loop :)
